#!/usr/bin/env node
/**
 * Flxify build script
 *
 * Reads lib modules from scripts/lib/ and scripts from scripts/.
 * Generates a fully self-contained app.js that works offline and with file:// URLs.
 * No `new Function()` or `eval()` in generated output — CSP-compatible.
 *
 * Usage: node build_app.js
 */

const fs = require('fs');
const path = require('path');

const SCRIPTS_DIR = path.join(__dirname, 'scripts');
const LIB_DIR = path.join(SCRIPTS_DIR, 'lib');
const OUTPUT = path.join(__dirname, 'app.js');

// ---- Auto-discover lib modules ----
const libFiles = fs.readdirSync(LIB_DIR)
  .filter(f => f.endsWith('.js'))
  .sort();

// ---- Auto-discover scripts ----
const scriptFiles = fs.readdirSync(SCRIPTS_DIR)
  .filter(f => f.endsWith('.js'))
  .sort();

// ---- Parse script metadata at build time ----
function parseMetadata(source, filename) {
  const metaMatch = source.match(/\/\*\*([\s\S]*?)\*\*\//);
  if (!metaMatch) {
    console.warn(`  WARNING: No metadata block in ${filename}, skipping`);
    return null;
  }
  const cleanedJson = metaMatch[1].trim().replace(/,\s*([\]}])/g, '$1');
  try {
    return JSON.parse(cleanedJson);
  } catch (e) {
    console.warn(`  WARNING: Invalid metadata JSON in ${filename}: ${e.message}`);
    return null;
  }
}

// ---- Read and validate all scripts ----
const scriptEntries = [];
for (const file of scriptFiles) {
  const source = fs.readFileSync(path.join(SCRIPTS_DIR, file), 'utf-8');
  const metadata = parseMetadata(source, file);
  if (!metadata) continue;
  scriptEntries.push({ file, source, metadata });
}

// ---- Read lib modules ----
const libEntries = [];
for (const file of libFiles) {
  const source = fs.readFileSync(path.join(LIB_DIR, file), 'utf-8');
  const name = file.replace(/\.js$/, '');
  libEntries.push({ file, name, source });
}

console.log(`Found ${libEntries.length} lib modules and ${scriptEntries.length} scripts.`);

// ---- Generate app.js ----
let output = `// Flxify - app.js
// Generated by build_app.js - do not edit directly.
// Edit scripts in scripts/ then run: node build_app.js

(function() {

// ============================================================
// 1. Module System (require shim)
// ============================================================

var flxifyModules = {};

function require(modulePath) {
  if (typeof modulePath === 'string' && modulePath.startsWith('@flxify/')) {
    var name = modulePath.replace('@flxify/', '').replace('.js', '');
    if (flxifyModules[name]) return flxifyModules[name];
    console.warn('Module not found: ' + name);
  }
  return null;
}

// ============================================================
// 2. Lib Modules (inlined at build time)
// ============================================================

`;

// Generate each lib module as direct code (no new Function)
for (const lib of libEntries) {
  output += `// --- ${lib.name} ---\n`;
  output += `(function() {\n`;
  output += `  var module = { exports: {} };\n`;
  output += `  var exports = module.exports;\n`;
  output += `  (function(exports, module) {\n`;
  output += lib.source;
  output += `\n  }).call(module.exports, module.exports, module);\n`;
  output += `  flxifyModules[${JSON.stringify(lib.name)}] = module.exports;\n`;
  output += `})();\n\n`;
}

output += `
// ============================================================
// 3. Script Registry (pre-compiled at build time)
// ============================================================

var scripts = [];

`;

// Generate each script as a pre-compiled object with execute function
for (const entry of scriptEntries) {
  const m = entry.metadata;
  output += `scripts.push({\n`;
  output += `  name: ${JSON.stringify(m.name || 'Unnamed')},\n`;
  output += `  description: ${JSON.stringify(m.description || '')},\n`;
  output += `  author: ${JSON.stringify(m.author || '')},\n`;
  output += `  icon: ${JSON.stringify(m.icon || '')},\n`;
  output += `  tags: ${JSON.stringify(m.tags || '')},\n`;
  output += `  execute: function(require, state) {\n`;
  output += entry.source;
  output += `\n    if (typeof main === "function") main(state);\n`;
  output += `  }\n`;
  output += `});\n\n`;
}

output += `scripts.sort(function(a, b) { return a.name.localeCompare(b.name); });

// ============================================================
// 4. Toast System
// ============================================================

function showToast(message, type) {
  var container = document.getElementById('toast');
  var el = document.createElement('div');
  el.className = 'toast-message ' + (type || 'info');
  el.textContent = message;
  container.appendChild(el);
  setTimeout(function() {
    if (el.parentNode) el.parentNode.removeChild(el);
  }, 3000);
}

// ============================================================
// 5. BoopState Class
// ============================================================

function BoopState(fullText, selectionStart, selectionEnd) {
  this._fullText = fullText;
  this._selectionStart = selectionStart;
  this._selectionEnd = selectionEnd;
  this._selection = (selectionStart !== selectionEnd)
    ? fullText.substring(selectionStart, selectionEnd)
    : null;
  this._isSelection = this._selection !== null;
  this._insertText = null;
}

Object.defineProperty(BoopState.prototype, 'fullText', {
  get: function() { return this._fullText; },
  set: function(val) { this._fullText = val; }
});

Object.defineProperty(BoopState.prototype, 'selection', {
  get: function() { return this._selection; },
  set: function(val) { this._selection = val; }
});

Object.defineProperty(BoopState.prototype, 'isSelection', {
  get: function() { return this._isSelection; }
});

Object.defineProperty(BoopState.prototype, 'text', {
  get: function() {
    return this._isSelection ? this._selection : this._fullText;
  },
  set: function(val) {
    if (this._isSelection) {
      this._selection = val;
    } else {
      this._fullText = val;
    }
  }
});

BoopState.prototype.postError = function(msg) { showToast(msg, 'error'); };
BoopState.prototype.postInfo = function(msg) { showToast(msg, 'info'); };
BoopState.prototype.insert = function(text) { this._insertText = text; };

// ============================================================
// 6. Script Executor
// ============================================================

function executeScript(script) {
  var cm = window.cmEditor;
  var fullText = cm.state.doc.toString();
  var selFrom = cm.state.selection.main.from;
  var selTo = cm.state.selection.main.to;
  var state = new BoopState(fullText, selFrom, selTo);

  try {
    script.execute(require, state);
  } catch (e) {
    showToast('Error: ' + e.message, 'error');
    console.error('Script execution error:', e);
    return;
  }

  // Apply results back to CodeMirror editor
  if (state._insertText !== null) {
    cm.dispatch({
      changes: { from: selFrom, to: selTo, insert: state._insertText },
      selection: { anchor: selFrom + state._insertText.length }
    });
  } else if (state._isSelection && state._selection !== null) {
    cm.dispatch({
      changes: { from: state._selectionStart, to: state._selectionEnd, insert: state._selection },
      selection: { anchor: state._selectionStart, head: state._selectionStart + state._selection.length }
    });
  } else {
    cm.dispatch({
      changes: { from: 0, to: cm.state.doc.length, insert: state._fullText }
    });
  }
}

// ============================================================
// 7. Command Palette
// ============================================================

var palette = document.getElementById('command-palette');
var searchInput = document.getElementById('search');
var resultsList = document.getElementById('results');
var activeIndex = 0;
var filteredScripts = [];

function showPalette() {
  palette.classList.remove('hidden');
  searchInput.value = '';
  filterScripts('');
  searchInput.focus();
}

function hidePalette() {
  palette.classList.add('hidden');
  if (window.cmEditor) window.cmEditor.focus();
}

function togglePalette() {
  if (palette.classList.contains('hidden')) {
    showPalette();
  } else {
    hidePalette();
  }
}

function fuzzyScore(query, text) {
  if (!query) return 1;
  var lowerQuery = query.toLowerCase();
  var lowerText = text.toLowerCase();

  if (lowerText === lowerQuery) return 100;
  if (lowerText.startsWith(lowerQuery)) return 80;
  if (lowerText.includes(lowerQuery)) return 60;

  var qi = 0;
  var consecutive = 0;
  var maxConsecutive = 0;
  var matched = 0;
  for (var ti = 0; ti < lowerText.length && qi < lowerQuery.length; ti++) {
    if (lowerText[ti] === lowerQuery[qi]) {
      qi++;
      matched++;
      consecutive++;
      if (consecutive > maxConsecutive) maxConsecutive = consecutive;
    } else {
      consecutive = 0;
    }
  }
  if (qi < lowerQuery.length) return 0;
  return 20 + maxConsecutive * 5 + matched;
}

function filterScripts(query) {
  if (!query) {
    filteredScripts = scripts.slice();
  } else {
    var scored = scripts.map(function(s) {
      var nameScore = fuzzyScore(query, s.name) * 0.9;
      var tagScore = fuzzyScore(query, s.tags) * 0.6;
      var descScore = fuzzyScore(query, s.description) * 0.2;
      var score = Math.max(nameScore, tagScore, descScore);
      return { script: s, score: score };
    }).filter(function(s) { return s.score > 0; });
    scored.sort(function(a, b) { return b.score - a.score; });
    filteredScripts = scored.map(function(s) { return s.script; });
  }
  activeIndex = 0;
  renderResults();
}

var animalEmojis = [
  '🐶','🐱','🐭','🐹','🐰','🦊','🐻','🐼','🐨','🐯',
  '🦁','🐮','🐷','🐸','🐵','🐔','🐧','🐦','🦆','🦅',
  '🦉','🐺','🐗','🐴','🦄','🐝','🦋','🐌','🐞','🐢',
  '🐍','🦎','🐙','🦑','🦐','🦀','🐡','🐠','🐟','🐬',
  '🐳','🦈','🐊','🐆','🦓','🦍','🐘','🦛','🦏','🐪',
  '🦒','🦘','🐃','🐄','🐎','🐖','🐏','🐑','🦙','🐐',
  '🦌','🐕','🐩','🐈','🦃','🦚','🦜','🦢','🦩','🐇',
  '🦝','🦨','🦦','🦥','🐁','🐿','🦔','🦫','🕊','🐓'
];

function getScriptEmoji(name) {
  var hash = 0;
  for (var i = 0; i < name.length; i++) {
    hash = ((hash << 5) - hash) + name.charCodeAt(i);
    hash |= 0;
  }
  return animalEmojis[Math.abs(hash) % animalEmojis.length];
}

function renderResults() {
  resultsList.innerHTML = '';
  filteredScripts.forEach(function(script, index) {
    var li = document.createElement('li');
    if (index === activeIndex) li.className = 'active';

    var nameSpan = document.createElement('span');
    nameSpan.className = 'script-name';
    nameSpan.textContent = getScriptEmoji(script.name) + '  ' + script.name;

    var descSpan = document.createElement('span');
    descSpan.className = 'script-desc';
    descSpan.textContent = script.description;

    li.appendChild(nameSpan);
    li.appendChild(descSpan);

    li.addEventListener('click', function() {
      executeScript(script);
      hidePalette();
    });

    resultsList.appendChild(li);
  });

  var activeEl = resultsList.querySelector('.active');
  if (activeEl) activeEl.scrollIntoView({ block: 'nearest' });
}

// ============================================================
// 8. Event Listeners
// ============================================================

document.addEventListener('keydown', function(e) {
  if ((e.metaKey || e.ctrlKey) && e.key === 'b') {
    e.preventDefault();
    togglePalette();
  }
});

searchInput.addEventListener('input', function() {
  filterScripts(searchInput.value);
});

searchInput.addEventListener('keydown', function(e) {
  if (e.key === 'ArrowDown') {
    e.preventDefault();
    if (activeIndex < filteredScripts.length - 1) {
      activeIndex++;
      renderResults();
    }
  } else if (e.key === 'ArrowUp') {
    e.preventDefault();
    if (activeIndex > 0) {
      activeIndex--;
      renderResults();
    }
  } else if (e.key === 'Enter') {
    e.preventDefault();
    if (filteredScripts[activeIndex]) {
      executeScript(filteredScripts[activeIndex]);
      hidePalette();
    }
  } else if (e.key === 'Escape') {
    e.preventDefault();
    hidePalette();
  }
});

palette.addEventListener('click', function(e) {
  if (e.target === palette) {
    hidePalette();
  }
});

// ============================================================
// 9. Initialize
// ============================================================

console.log('Flxify loaded: ' + scripts.length + ' scripts available.');

// Auto-script detection for tool pages
if (window.flxifyAutoScript) {
  var targetScript = scripts.find(function(s) {
    return s.name === window.flxifyAutoScript;
  });
  if (targetScript) {
    console.log('Auto-selected script: ' + targetScript.name);
  }
}

// FAQ toggle for tool pages
document.querySelectorAll('.faq-question').forEach(function(q) {
  q.addEventListener('click', function() {
    this.parentElement.classList.toggle('open');
  });
});

// Mobile menu button
var mobileBtn = document.getElementById('mobile-menu-btn');
if (mobileBtn) mobileBtn.addEventListener('click', togglePalette);

// Palette close button (visible on mobile)
var paletteCloseBtn = document.getElementById('palette-close');
if (paletteCloseBtn) paletteCloseBtn.addEventListener('click', hidePalette);

// Theme system
var cmThemeMap = {
  'standard-light': function() { return window.flxifyLightTheme; },
  'standard-dark': function() { return window.flxifyDarkTheme; },
  'cyber-neon': function() { return window.flxifyCyberNeonTheme; },
  'nordic-frost': function() { return window.flxifyNordicFrostTheme; },
  'monokai-pro': function() { return window.flxifyMonokaiProTheme; },
  'oled-stealth': function() { return window.flxifyOledStealthTheme; }
};

function applyTheme(themeKey) {
  document.documentElement.setAttribute('data-theme', themeKey);
  try { localStorage.setItem('flxify-theme', themeKey); } catch(e) {}

  // Update CM6 editor theme
  var getTheme = cmThemeMap[themeKey];
  if (getTheme && window.cmEditor && window.flxifyThemeConf) {
    var cmTheme = getTheme();
    if (cmTheme) {
      window.cmEditor.dispatch({
        effects: window.flxifyThemeConf.reconfigure(cmTheme)
      });
    }
  }

  // Update dropdown button label and dot
  var label = document.querySelector('.theme-label');
  var dot = document.querySelector('#theme-toggle .theme-dot');
  var activeOption = document.querySelector('.theme-option[data-theme="' + themeKey + '"]');
  if (label && activeOption) {
    label.textContent = activeOption.getAttribute('data-label');
  }
  if (dot && activeOption) {
    dot.style.background = activeOption.getAttribute('data-dot');
  }

  // Update active state in dropdown
  document.querySelectorAll('.theme-option').forEach(function(opt) {
    opt.classList.toggle('active', opt.getAttribute('data-theme') === themeKey);
  });
}

// Theme dropdown toggle
var themeToggle = document.getElementById('theme-toggle');
var themeDropdown = document.getElementById('theme-dropdown');

if (themeToggle && themeDropdown) {
  themeToggle.addEventListener('click', function(e) {
    e.stopPropagation();
    themeDropdown.classList.toggle('open');
  });

  document.querySelectorAll('.theme-option').forEach(function(opt) {
    opt.addEventListener('click', function() {
      applyTheme(this.getAttribute('data-theme'));
      themeDropdown.classList.remove('open');
    });
  });

  // Close dropdown when clicking outside
  document.addEventListener('click', function() {
    themeDropdown.classList.remove('open');
  });
}

// Load saved theme on init
var savedTheme = 'standard-dark';
try { savedTheme = localStorage.getItem('flxify-theme') || 'standard-dark'; } catch(e) {}
document.documentElement.setAttribute('data-theme', savedTheme);

// Apply CM6 theme when editor is ready
function applyCMThemeOnReady() {
  if (window.cmEditor && window.flxifyThemeConf) {
    applyTheme(savedTheme);
  } else {
    document.addEventListener('cm-ready', function() {
      applyTheme(savedTheme);
    });
  }
}
applyCMThemeOnReady();

// Directory search filter
var dirSearch = document.getElementById('directory-search');
if (dirSearch) {
  dirSearch.addEventListener('input', function() {
    var query = this.value.toLowerCase();
    document.querySelectorAll('.tool-card').forEach(function(card) {
      var name = card.querySelector('.tool-card-name').textContent.toLowerCase();
      var desc = card.querySelector('.tool-card-desc').textContent.toLowerCase();
      card.style.display = (name.includes(query) || desc.includes(query)) ? '' : 'none';
    });
    document.querySelectorAll('.category-section').forEach(function(section) {
      var visible = section.querySelectorAll('.tool-card[style=""], .tool-card:not([style])');
      section.style.display = visible.length > 0 ? '' : 'none';
    });
  });
}

// Service worker registration
if ('serviceWorker' in navigator) {
  navigator.serviceWorker.register('/service-worker.js').catch(function() {});
}

})();
`;

fs.writeFileSync(OUTPUT, output, 'utf-8');
console.log(`Generated app.js (${(output.length / 1024).toFixed(1)} KB)`);

// ============================================================
// SEO Page Generation
// ============================================================

const TOOLS_DIR = path.join(__dirname, 'tools');
const SEO_DATA_FILE = path.join(__dirname, 'seo-data.json');
const SITE_URL = 'https://flxify.dev';

// ---- Load SEO data ----
let seoData = { _categories: {}, _customMeta: {} };
if (fs.existsSync(SEO_DATA_FILE)) {
  seoData = JSON.parse(fs.readFileSync(SEO_DATA_FILE, 'utf-8'));
}

// ---- Helper: generate slug from script name ----
function nameToSlug(name) {
  return name.toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
}

// ---- Helper: find category for a script ----
function findCategory(fileKey) {
  for (const [cat, files] of Object.entries(seoData._categories || {})) {
    if (files.includes(fileKey)) return cat;
  }
  return 'Developer Utilities';
}

// ---- Helper: auto-generate SEO title from script name ----
function autoTitle(name) {
  const t = `${name} - Free Online Developer Tool`;
  return t.length > 65 ? `${name} - Free Online Tool` : t;
}

// ---- Helper: auto-generate meta description ----
function autoMetaDesc(name, description) {
  const d = `${description} Free online ${name.toLowerCase()} tool. 100% client-side, your data never leaves your browser.`;
  return d.length > 160 ? d.substring(0, 155) + '...' : d;
}

// ---- Helper: auto-generate how-to steps ----
function autoHowToSteps(name) {
  return [
    `Open the ${name} tool on Flxify`,
    'Paste or type your text into the editor',
    `Press Cmd+B (or Ctrl+B) and select "${name}" from the command palette`,
    'View the transformed result in the editor',
    'Copy the output for your use'
  ];
}

// ---- Helper: auto-generate use case content ----
function autoUseCaseContent(name, description) {
  return `${description} This tool helps developers quickly transform text data without leaving their browser. All processing happens client-side, ensuring your data remains private and secure.`;
}

// ---- Helper: auto-generate FAQs ----
function autoFaqs(name) {
  return [
    { question: `Is the ${name} tool free?`, answer: `Yes, ${name} on Flxify is completely free to use with no limits or sign-up required.` },
    { question: `Is my data safe when using ${name}?`, answer: 'All processing happens in your browser. Your data never leaves your device and is never sent to any server.' },
    { question: `Can I use ${name} offline?`, answer: 'After the initial page load, the tool works offline. All processing is done client-side with no server dependency.' }
  ];
}

// ---- Helper: find related tools ----
function findRelatedTools(fileKey, allEntries) {
  const cat = findCategory(fileKey);
  const catMembers = (seoData._categories[cat] || []).filter(f => f !== fileKey);
  return catMembers.slice(0, 4);
}

// ---- Helper: escape HTML ----
function escHtml(str) {
  return String(str).replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');
}

// ---- Read CodeMirror module script from index.html ----
const indexHtml = fs.readFileSync(path.join(__dirname, 'index.html'), 'utf-8');
const cmScriptMatch = indexHtml.match(/<script type="module">([\s\S]*?)<\/script>/);
const cmModuleScript = cmScriptMatch ? cmScriptMatch[1] : '';

// ---- Build script SEO entries ----
const seoEntries = [];
for (const entry of scriptEntries) {
  const fileKey = entry.file.replace(/\.js$/, '');
  const m = entry.metadata;
  const custom = (seoData._customMeta || {})[fileKey] || {};
  const slug = nameToSlug(m.name || fileKey);
  const category = findCategory(fileKey);
  const related = findRelatedTools(fileKey, scriptEntries);

  seoEntries.push({
    fileKey,
    slug,
    name: m.name || 'Unnamed',
    description: m.description || '',
    tags: m.tags || '',
    category,
    title: custom.title || autoTitle(m.name || fileKey),
    metaDescription: custom.metaDescription || autoMetaDesc(m.name || fileKey, m.description || ''),
    keywords: custom.keywords || (m.tags || '').split(',').map(t => t.trim()).filter(Boolean),
    howToSteps: autoHowToSteps(m.name || fileKey),
    useCaseContent: autoUseCaseContent(m.name || fileKey, m.description || ''),
    faqs: autoFaqs(m.name || fileKey),
    relatedTools: related
  });
}

console.log(`Generating SEO pages for ${seoEntries.length} scripts...`);

// ---- Ensure tools directory exists ----
if (!fs.existsSync(TOOLS_DIR)) fs.mkdirSync(TOOLS_DIR, { recursive: true });

// ---- Generate each tool page ----
for (const entry of seoEntries) {
  const toolDir = path.join(TOOLS_DIR, entry.slug);
  if (!fs.existsSync(toolDir)) fs.mkdirSync(toolDir, { recursive: true });

  const relatedHtml = entry.relatedTools.map(rk => {
    const re = seoEntries.find(e => e.fileKey === rk);
    if (!re) return '';
    return `        <a href="../${re.slug}/" class="related-card">${escHtml(re.name)}</a>`;
  }).filter(Boolean).join('\n');

  const faqJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'FAQPage',
    mainEntity: entry.faqs.map(f => ({
      '@type': 'Question',
      name: f.question,
      acceptedAnswer: { '@type': 'Answer', text: f.answer }
    }))
  };

  const howToJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'HowTo',
    name: `How to use ${entry.name}`,
    step: entry.howToSteps.map((s, i) => ({
      '@type': 'HowToStep',
      position: i + 1,
      text: s
    }))
  };

  const webAppJsonLd = {
    '@context': 'https://schema.org',
    '@type': 'WebApplication',
    name: `${entry.name} - Flxify`,
    url: `${SITE_URL}/tools/${entry.slug}/`,
    description: entry.metaDescription,
    applicationCategory: 'DeveloperApplication',
    operatingSystem: 'Any',
    offers: { '@type': 'Offer', price: '0', priceCurrency: 'USD' }
  };

  // Adjust CodeMirror script paths for tool pages (../../ instead of ./)
  let toolCmScript = cmModuleScript
    .replace(/from 'https:\/\/esm\.sh\//g, "from 'https://esm.sh/");

  const toolPageHtml = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>${escHtml(entry.title)} | Flxify</title>
  <meta name="description" content="${escHtml(entry.metaDescription)}">
  <meta name="keywords" content="${escHtml(entry.keywords.join(', '))}">
  <link rel="canonical" href="${SITE_URL}/tools/${entry.slug}/">
  <link rel="icon" type="image/png" href="../../logo.png">
  <link rel="manifest" href="../../manifest.json">
  <meta name="theme-color" content="#252526">
  <link rel="apple-touch-icon" href="../../icons/icon-192.png">
  <link rel="preconnect" href="https://esm.sh">

  <meta property="og:type" content="website">
  <meta property="og:title" content="${escHtml(entry.title)}">
  <meta property="og:description" content="${escHtml(entry.metaDescription)}">
  <meta property="og:url" content="${SITE_URL}/tools/${entry.slug}/">
  <meta property="og:site_name" content="Flxify">
  <meta property="og:image" content="${SITE_URL}/logo.png">

  <meta name="twitter:card" content="summary">
  <meta name="twitter:title" content="${escHtml(entry.title)}">
  <meta name="twitter:description" content="${escHtml(entry.metaDescription)}">
  <meta name="twitter:image" content="${SITE_URL}/logo.png">

  <script type="application/ld+json">${JSON.stringify(webAppJsonLd)}</script>
  <script type="application/ld+json">${JSON.stringify(faqJsonLd)}</script>
  <script type="application/ld+json">${JSON.stringify(howToJsonLd)}</script>

  <link rel="stylesheet" href="../../style.css">
  <script>(function(){var t=localStorage.getItem('flxify-theme')||'standard-dark';document.documentElement.setAttribute('data-theme',t);})();</script>
</head>
<body class="tool-page">
  <div id="top-bar">
    <a href="../../" class="top-bar-home">
      <img src="../../logo.png" alt="Flxify" class="app-logo">
      <span class="app-title">Flxify</span>
    </a>
    <button id="mobile-menu-btn" class="mobile-menu-btn" title="Open command palette">
      <svg width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round"><line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="18" x2="21" y2="18"/></svg>
    </button>
    <nav class="top-bar-nav">
      <a href="../" class="nav-link">All Tools</a>
      <a href="https://marketplace.visualstudio.com/items?itemName=flxify.flxify" target="_blank" rel="noopener" class="vscode-ext-link" title="Get the VS Code Extension">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor"><path d="M17.583.063a1.5 1.5 0 0 1 1.342.825l4.5 9.75a1.5 1.5 0 0 1 0 1.272l-4.5 9.75a1.5 1.5 0 0 1-1.342.84H6.417a1.5 1.5 0 0 1-1.342-.825l-4.5-9.75a1.5 1.5 0 0 1 0-1.272l4.5-9.75A1.5 1.5 0 0 1 6.417.038h11.166zM12 6.75a5.25 5.25 0 1 0 0 10.5 5.25 5.25 0 0 0 0-10.5z"/></svg>
        <span>VS Code</span>
      </a>
      <div id="theme-selector" class="theme-selector">
        <button id="theme-toggle" class="theme-toggle-btn" aria-label="Change theme" title="Change theme">
          <span class="theme-dot"></span>
          <span class="theme-label">Standard Dark</span>
          <svg width="12" height="12" viewBox="0 0 12 12" fill="none"><path d="M3 4.5L6 7.5L9 4.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>
        </button>
        <div id="theme-dropdown" class="theme-dropdown">
          <button class="theme-option" data-theme="standard-light" data-label="Standard Light" data-dot="#0066cc">
            <span class="theme-dot" style="background:#0066cc"></span> Standard Light
          </button>
          <button class="theme-option" data-theme="standard-dark" data-label="Standard Dark" data-dot="#094771">
            <span class="theme-dot" style="background:#094771"></span> Standard Dark
          </button>
          <button class="theme-option" data-theme="cyber-neon" data-label="Cyber Neon" data-dot="#00f5ff">
            <span class="theme-dot" style="background:#00f5ff"></span> Cyber Neon
          </button>
          <button class="theme-option" data-theme="nordic-frost" data-label="Nordic Frost" data-dot="#81a1c1">
            <span class="theme-dot" style="background:#81a1c1"></span> Nordic Frost
          </button>
          <button class="theme-option" data-theme="monokai-pro" data-label="Monokai Pro" data-dot="#ab9df2">
            <span class="theme-dot" style="background:#ab9df2"></span> Monokai Pro
          </button>
          <button class="theme-option" data-theme="oled-stealth" data-label="OLED Stealth" data-dot="#0066ff">
            <span class="theme-dot" style="background:#0066ff"></span> OLED Stealth
          </button>
        </div>
      </div>
    </nav>
  </div>

  <div id="tool-header">
    <h1>${escHtml(entry.name)}</h1>
    <p class="tool-subtitle">${escHtml(entry.description)} &mdash; Free Online Developer Utility</p>
    <span class="privacy-badge">
      <svg width="12" height="12" viewBox="0 0 24 24" fill="currentColor"><path d="M18 8h-1V6c0-2.76-2.24-5-5-5S7 3.24 7 6v2H6c-1.1 0-2 .9-2 2v10c0 1.1.9 2 2 2h12c1.1 0 2-.9 2-2V10c0-1.1-.9-2-2-2zm-6 9c-1.1 0-2-.9-2-2s.9-2 2-2 2 .9 2 2-.9 2-2 2zm3.1-9H8.9V6c0-1.71 1.39-3.1 3.1-3.1 1.71 0 3.1 1.39 3.1 3.1v2z"/></svg>
      100% Client-Side &middot; Your data never leaves your browser
    </span>
  </div>

  <div id="editor-wrapper">
    <div id="editor"></div>
    <div id="editor-hint">Press <kbd id="hint-shortcut-key">Cmd+B</kbd> to open the command palette</div>
  </div>

  <div id="command-palette" class="hidden">
    <div id="palette-container">
      <div id="palette-header">
        <input id="search" type="text" placeholder="Type a command..." autocomplete="off" spellcheck="false">
        <button id="palette-close" type="button" aria-label="Close">&times;</button>
      </div>
      <ul id="results"></ul>
    </div>
  </div>

  <div id="toast"></div>

  <div id="seo-content">
    <h2>How to Use ${escHtml(entry.name)}</h2>
    <section class="how-to-section">
      <ol>
${entry.howToSteps.map(s => `        <li>${escHtml(s)}</li>`).join('\n')}
      </ol>
    </section>

    <h2>Why Use ${escHtml(entry.name)}?</h2>
    <section class="use-case-section">
      <p>${escHtml(entry.useCaseContent)}</p>
    </section>

${relatedHtml ? `    <h2>Related Tools</h2>
    <section class="related-tools-section">
      <div class="related-grid">
${relatedHtml}
      </div>
    </section>
` : ''}
    <h2>Frequently Asked Questions</h2>
    <section class="faq-section">
${entry.faqs.map(f => `      <div class="faq-item">
        <div class="faq-question">${escHtml(f.question)}</div>
        <div class="faq-answer">${escHtml(f.answer)}</div>
      </div>`).join('\n')}
    </section>

    <a href="../" class="all-tools-cta">Browse All ${seoEntries.length} Developer Tools</a>
  </div>

  <div id="status-bar">
    <span id="credit">
      Crafted with <span class="heart">&hearts;</span> in Berlin by Ahmed El Taweel
    </span>
    <span id="shortcut-hint"></span>
  </div>

  <script>window.flxifyAutoScript = ${JSON.stringify(entry.name)};</script>
  <script type="module">${toolCmScript}</script>
  <script defer src="../../app.js"></script>
</body>
</html>`;

  fs.writeFileSync(path.join(toolDir, 'index.html'), toolPageHtml, 'utf-8');
}

console.log(`  Generated ${seoEntries.length} tool pages in tools/`);

// ---- Generate directory page ----
const categorized = {};
for (const entry of seoEntries) {
  if (!categorized[entry.category]) categorized[entry.category] = [];
  categorized[entry.category].push(entry);
}

// Sort categories to match seo-data.json order
const categoryOrder = Object.keys(seoData._categories || {});
const sortedCategories = categoryOrder.filter(c => categorized[c]);
// Add any categories not in the order
for (const c of Object.keys(categorized)) {
  if (!sortedCategories.includes(c)) sortedCategories.push(c);
}

let directorySections = '';
for (const cat of sortedCategories) {
  const entries = categorized[cat] || [];
  entries.sort((a, b) => a.name.localeCompare(b.name));
  directorySections += `    <section class="category-section">
      <h2>${escHtml(cat)}</h2>
      <div class="tool-grid">
${entries.map(e => `        <a href="${e.slug}/" class="tool-card">
          <div class="tool-card-name">${escHtml(e.name)}</div>
          <div class="tool-card-desc">${escHtml(e.description)}</div>
        </a>`).join('\n')}
      </div>
    </section>
`;
}

const directoryJsonLd = {
  '@context': 'https://schema.org',
  '@type': 'ItemList',
  name: 'Flxify Developer Tools',
  description: `${seoEntries.length} free online developer text utilities`,
  numberOfItems: seoEntries.length,
  itemListElement: seoEntries.map((e, i) => ({
    '@type': 'ListItem',
    position: i + 1,
    name: e.name,
    url: `${SITE_URL}/tools/${e.slug}/`
  }))
};

const directoryPage = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>All Developer Tools - Free Online Utilities | Flxify</title>
  <meta name="description" content="Browse ${seoEntries.length}+ free online developer text utilities: JSON formatters, encoders, hash generators, converters, and more. 100% client-side.">
  <link rel="canonical" href="${SITE_URL}/tools/">
  <link rel="icon" type="image/png" href="../logo.png">
  <link rel="manifest" href="../manifest.json">
  <meta name="theme-color" content="#252526">
  <link rel="apple-touch-icon" href="../icons/icon-192.png">

  <meta property="og:type" content="website">
  <meta property="og:title" content="All Developer Tools - Free Online Utilities | Flxify">
  <meta property="og:description" content="${seoEntries.length}+ free text transformation tools for developers.">
  <meta property="og:url" content="${SITE_URL}/tools/">
  <meta property="og:site_name" content="Flxify">

  <meta name="twitter:card" content="summary">
  <meta name="twitter:title" content="All Developer Tools | Flxify">
  <meta name="twitter:description" content="${seoEntries.length}+ free text transformation tools for developers.">

  <script type="application/ld+json">${JSON.stringify(directoryJsonLd)}</script>

  <link rel="stylesheet" href="../style.css">
  <script>(function(){var t=localStorage.getItem('flxify-theme')||'standard-dark';document.documentElement.setAttribute('data-theme',t);})();</script>
</head>
<body class="directory-page">
  <div id="top-bar">
    <a href="../" class="top-bar-home">
      <img src="../logo.png" alt="Flxify" class="app-logo">
      <span class="app-title">Flxify</span>
    </a>
    <nav class="top-bar-nav">
      <a href="https://marketplace.visualstudio.com/items?itemName=flxify.flxify" target="_blank" rel="noopener" class="vscode-ext-link" title="Get the VS Code Extension">
        <svg width="14" height="14" viewBox="0 0 24 24" fill="currentColor"><path d="M17.583.063a1.5 1.5 0 0 1 1.342.825l4.5 9.75a1.5 1.5 0 0 1 0 1.272l-4.5 9.75a1.5 1.5 0 0 1-1.342.84H6.417a1.5 1.5 0 0 1-1.342-.825l-4.5-9.75a1.5 1.5 0 0 1 0-1.272l4.5-9.75A1.5 1.5 0 0 1 6.417.038h11.166zM12 6.75a5.25 5.25 0 1 0 0 10.5 5.25 5.25 0 0 0 0-10.5z"/></svg>
        <span>VS Code Extension</span>
      </a>
      <div id="theme-selector" class="theme-selector">
        <button id="theme-toggle" class="theme-toggle-btn" aria-label="Change theme" title="Change theme">
          <span class="theme-dot"></span>
          <span class="theme-label">Standard Dark</span>
          <svg width="12" height="12" viewBox="0 0 12 12" fill="none"><path d="M3 4.5L6 7.5L9 4.5" stroke="currentColor" stroke-width="1.5" stroke-linecap="round" stroke-linejoin="round"/></svg>
        </button>
        <div id="theme-dropdown" class="theme-dropdown">
          <button class="theme-option" data-theme="standard-light" data-label="Standard Light" data-dot="#0066cc">
            <span class="theme-dot" style="background:#0066cc"></span> Standard Light
          </button>
          <button class="theme-option" data-theme="standard-dark" data-label="Standard Dark" data-dot="#094771">
            <span class="theme-dot" style="background:#094771"></span> Standard Dark
          </button>
          <button class="theme-option" data-theme="cyber-neon" data-label="Cyber Neon" data-dot="#00f5ff">
            <span class="theme-dot" style="background:#00f5ff"></span> Cyber Neon
          </button>
          <button class="theme-option" data-theme="nordic-frost" data-label="Nordic Frost" data-dot="#81a1c1">
            <span class="theme-dot" style="background:#81a1c1"></span> Nordic Frost
          </button>
          <button class="theme-option" data-theme="monokai-pro" data-label="Monokai Pro" data-dot="#ab9df2">
            <span class="theme-dot" style="background:#ab9df2"></span> Monokai Pro
          </button>
          <button class="theme-option" data-theme="oled-stealth" data-label="OLED Stealth" data-dot="#0066ff">
            <span class="theme-dot" style="background:#0066ff"></span> OLED Stealth
          </button>
        </div>
      </div>
    </nav>
  </div>

  <div class="tool-directory">
    <h1>All Developer Tools</h1>
    <p class="directory-subtitle">${seoEntries.length} free online text transformation utilities for developers</p>
    <input type="text" id="directory-search" class="directory-search" placeholder="Search tools..." autocomplete="off">

${directorySections}
  </div>

  <div id="status-bar">
    <span id="credit">
      Crafted with <span class="heart">&hearts;</span> in Berlin by Ahmed El Taweel
    </span>
  </div>

  <div id="toast"></div>
  <script defer src="../app.js"></script>
</body>
</html>`;

fs.writeFileSync(path.join(TOOLS_DIR, 'index.html'), directoryPage, 'utf-8');
console.log('  Generated tools/index.html (directory page)');

// ---- Generate sitemap.xml ----
const today = new Date().toISOString().split('T')[0];
let sitemap = `<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
  <url>
    <loc>${SITE_URL}/</loc>
    <lastmod>${today}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>1.0</priority>
  </url>
  <url>
    <loc>${SITE_URL}/tools/</loc>
    <lastmod>${today}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.9</priority>
  </url>
`;
for (const entry of seoEntries) {
  sitemap += `  <url>
    <loc>${SITE_URL}/tools/${entry.slug}/</loc>
    <lastmod>${today}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.8</priority>
  </url>
`;
}
sitemap += '</urlset>\n';
fs.writeFileSync(path.join(__dirname, 'sitemap.xml'), sitemap, 'utf-8');
console.log('  Generated sitemap.xml');

// ---- Generate robots.txt ----
const robotsTxt = `User-agent: *
Allow: /
Sitemap: ${SITE_URL}/sitemap.xml
`;
fs.writeFileSync(path.join(__dirname, 'robots.txt'), robotsTxt, 'utf-8');
console.log('  Generated robots.txt');

console.log('SEO generation complete.');

// ---- Phase 3: Update script count in source files ----
// Replaces hardcoded script counts so they stay in sync automatically.
console.log(`\nPhase 3: Updating script count (${scriptEntries.length}) in source files...`);

const SCRIPT_COUNT = scriptEntries.length;

const SITEMAP_COUNT = SCRIPT_COUNT + 2; // homepage + directory + N tools

const countReplacements = [
  // [file, pattern, replacement] — pattern matches the old count in context
  // README.md
  ['README.md', /\*\*\d+ executable scripts\*\*/g, `**${SCRIPT_COUNT} executable scripts**`],
  ['README.md', /- \*\*\d+ scripts\*\*/g, `- **${SCRIPT_COUNT} scripts**`],
  ['README.md', /the same \d+ scripts/g, `the same ${SCRIPT_COUNT} scripts`],
  ['README.md', /all \d+ scripts\./g, `all ${SCRIPT_COUNT} scripts.`],
  ['README.md', /all \d+ scripts organized/g, `all ${SCRIPT_COUNT} scripts organized`],
  // SCRIPTS.md
  ['SCRIPTS.md', /All \d+ scripts/g, `All ${SCRIPT_COUNT} scripts`],
  // tui/README.md
  ['tui/README.md', /\*\*\d+ transformation scripts\*\*/g, `**${SCRIPT_COUNT} transformation scripts**`],
  ['tui/README.md', /\*\*\d+ scripts\*\*/g, `**${SCRIPT_COUNT} scripts**`],
  ['tui/README.md', /the same \d+ scripts/g, `the same ${SCRIPT_COUNT} scripts`],
  // tui/package.json
  ['tui/package.json', /Terminal text utility with \d+ transformation/g, `Terminal text utility with ${SCRIPT_COUNT} transformation`],
  // vscode-extension
  ['vscode-extension/package.json', /\d+\+ text transformation scripts for developers/g, `${SCRIPT_COUNT}+ text transformation scripts for developers`],
  ['vscode-extension/README.md', /\d+\+ text transformation scripts/g, `${SCRIPT_COUNT}+ text transformation scripts`],
  ['vscode-extension/README.md', /\d+\+ Built-in Scripts/g, `${SCRIPT_COUNT}+ Built-in Scripts`],
  // CLAUDE.md — current counts (not version history)
  ['CLAUDE.md', /with \d+ executable scripts accessible/g, `with ${SCRIPT_COUNT} executable scripts accessible`],
  ['CLAUDE.md', /\*\*\d+ scripts\*\* are auto-discovered/g, `**${SCRIPT_COUNT} scripts** are auto-discovered`],
  ['CLAUDE.md', /all \d+ scripts, BoopState/g, `all ${SCRIPT_COUNT} scripts, BoopState`],
  ['CLAUDE.md', /Source of truth for all \d+ scripts/g, `Source of truth for all ${SCRIPT_COUNT} scripts`],
  ['CLAUDE.md', /\d+ tool pages \+ directory/g, `${SCRIPT_COUNT} tool pages + directory`],
  ['CLAUDE.md', /all \d+ URLs \(homepage/g, `all ${SITEMAP_COUNT} URLs (homepage`],
  ['CLAUDE.md', /\+ directory \+ \d+ tools\)/g, `+ directory + ${SCRIPT_COUNT} tools)`],
  ['CLAUDE.md', /Loads \d+ scripts at runtime for TUI/g, `Loads ${SCRIPT_COUNT} scripts at runtime for TUI`],
  ['CLAUDE.md', /generates \d+ static tool pages/g, `generates ${SCRIPT_COUNT} static tool pages`],
  ['CLAUDE.md', /all \d+ scripts via Cmd/g, `all ${SCRIPT_COUNT} scripts via Cmd`],
  ['CLAUDE.md', /generates app\.js \+ \d+ tool pages/g, `generates app.js + ${SCRIPT_COUNT} tool pages`],
  ['CLAUDE.md', /for each of \d+ scripts/g, `for each of ${SCRIPT_COUNT} scripts`],
  ['CLAUDE.md', /\d+ URLs: homepage \+ directory \+ \d+ tools/g, `${SITEMAP_COUNT} URLs: homepage + directory + ${SCRIPT_COUNT} tools`],
  ['CLAUDE.md', /shares the same \d+ scripts/g, `shares the same ${SCRIPT_COUNT} scripts`],
  ['CLAUDE.md', /metadata validation \(all \d+ scripts\)/g, `metadata validation (all ${SCRIPT_COUNT} scripts)`],
  ['CLAUDE.md', /the same \d+ scripts\. Launches/g, `the same ${SCRIPT_COUNT} scripts. Launches`],
  // DOING.md
  ['DOING.md', /command palette \(\d+ scripts\)/g, `command palette (${SCRIPT_COUNT} scripts)`],
];

// Group replacements by file — read once, apply all patterns, write once
const replacementsByFile = {};
for (const [relPath, pattern, replacement] of countReplacements) {
  if (!replacementsByFile[relPath]) replacementsByFile[relPath] = [];
  replacementsByFile[relPath].push({ pattern, replacement });
}

let countUpdated = 0;
for (const [relPath, replacements] of Object.entries(replacementsByFile)) {
  const filePath = path.join(__dirname, relPath);
  let content = fs.readFileSync(filePath, 'utf-8');
  const original = content;
  for (const { pattern, replacement } of replacements) {
    content = content.replace(pattern, replacement);
  }
  if (content !== original) {
    fs.writeFileSync(filePath, content, 'utf-8');
    countUpdated++;
    console.log(`  Updated ${relPath}`);
  }
}
console.log(`Script count update complete (${countUpdated} files updated).`);
